# Generated by Django 4.0.2 on 2022-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('age_years', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
            ],
        ),
    ]
