# Generated by Django 4.0.2 on 2022-02-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0002_remove_children_age_months_remove_children_age_years_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Children',
        ),
    ]
