# Generated by Django 4.0.2 on 2022-02-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
