# Generated by Django 4.0.2 on 2022-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0005_rename_created_at_children_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='child_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
