# Generated by Django 4.0.2 on 2022-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0008_alter_children_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(default='Boy', max_length=4),
        ),
    ]
