# Generated by Django 4.0.2 on 2022-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0009_alter_children_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
