# Generated by Django 4.0.2 on 2022-02-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenApp', '0015_alter_children_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
